version: '3.4'

services:
  productdb:
    container_name: productdb
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  authenticationdb:
    container_name: authenticationdb
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=SwN12345678
      - ACCEPT_EULA=Y  
    ports:
      - "1433:1433"

  catalog.productservice:
    image: productservice
    ports:
      - "8002:80"

  catalog.authenticationservice:
    image: authenticationservice
    ports:
      - "8004:80"

  apigateway:
    image: apigateway
    ports:
      - "8080:80"
      - "8081:443"

volumes:
  postgres_data:
  pgadmin_data:
