name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output publish

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Images
      run: |
        docker build -t productservice ./ProductService
        docker build -t inventoryservice ./InventoryService
        docker build -t authenticationservice ./AuthenticationService
        docker build -t apigateway ./ApiGateway
        docker push productservice
        docker push inventoryservice
        docker push authenticationservice
        docker push apigateway

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f productservice.yaml
        kubectl apply -f inventoryservice.yaml
        kubectl apply -f authenticationservice.yaml
        kubectl apply -f apigateway.yaml
        kubectl apply -f ingress.yaml

